version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"

  db:
    image: postgres:17.0
    ports:
      - '5440:5432'
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - 'vy_university_postgres_python_final_exam:/var/lib/postgresql/data'

volumes:
  vy_university_postgres_python_final_exam:
